#!/usr/bin/env python

import os
import subprocess
import time

def get_curr_playing():
    try:
        result = subprocess.run(['rhythmbox-client', '--check-running'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if result.returncode != 0:
            return "No playing"
        result = subprocess.run(['rhythmbox-client', '--print-playing'], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
        curr_song = result.stdout.decode('utf-8').strip()
        # remove extension of song
        curr_song = os.path.splitext(curr_song)[0]
        length = len(curr_song)
        if length < 20:
            return curr_song
        else:
            unix_time = int(time.time())
            i = unix_time % (length - 18)
            return curr_song[i:i+19]
    except Exception as e:
        return f'Error: {e}'

if __name__ == '__main__':
    print(get_curr_playing())

